### ISSUE TITLE
Merge request of your bug fixes

### ISSUE THREAD

**Issue by johndoe75** [donSchoe/p2pool-n#11]
I feel honored that you have included https://github.com/johndoe75/p2pool-node-status which is my attempt to create a more modern and clean p2pool web interface to your p2pool repository.

But is it possible that if you have bug fixes you either open an issue on my repo or put in a merge request?  That way the main repo could stay more easily in sync with your code.

**Comment by donSchoe** [comment]
Hi, of course I can do that. I'm not aware of any fixes yet. Did I oversee them?
