### ISSUE TITLE
ADD SPA

### ISSUE THREAD

**Issue by mapleshadow** [donSchoe/p2pool-n#19]

**Comment by donSchoe** [comment]
Can you create a pull request?
https://github.com/SpainCoinProject/p2pool

**Comment by youvnor** [comment]
i will do it

**Comment by donSchoe** [comment]
@youvnor @Lovok
Sorry, but which one looks better for you guys? #23 or #25 ?
On first glance they seem to work both. I'm gonna merge #23 now and we'll see if something is missing?
 Agree / disagree ?
