### ISSUE TITLE
add frontend

### ISSUE THREAD

**Issue by donSchoe** [donSchoe/p2pool-n#8]
https://github.com/johndoe75/p2pool-node-status
http://vtc.coinpools.de:9171/static/

**Comment by mmouse-** [comment]
I will send a pull request for the frontend in the next hours.
I intend to put it in a directory called web-static.modern. So everybody is free to rename and use it instead of the existing frontend.

**Comment by donSchoe** [comment]
I'm not sure, shall we really keep the default one?

**Comment by erkmos** [comment]
Yes, some people prefer the old one, and p2pool-node-status doesn't seem to have stuff like detailed share information or graphs.

**Comment by mmouse-** [comment]
detailed graphs are in the old-old classic frontend, which I did include in the new one.
I think we better keep the default one for some time. We can remove it later on, if really nobody is using it any more.
